#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --mem=80gb
#SBATCH --tmp=60gb
#SBATCH -t 08:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=liux1299@umn.edu
#SBATCH -p ram256g,ram1t,amd2tb
#SBATCH -o %j.out
#SBATCH -e %j.err

set -e
set -o pipefail

# This calls SVs using Sniffles2

# Dependencies
module load samtools/1.9
module load python3/3.8.3_anaconda2020.07_mamba
# Activate conda environment
source activate /panfs/roc/groups/9/morrellp/liux1299/.conda/envs/sniffles_env

# User provided input arguments
BAM="/panfs/roc/groups/9/morrellp/gfrascar/Morex_IPK_85X/Morex_85X_sorted.bam"
REF="/panfs/roc/groups/9/morrellp/shared/References/Reference_Sequences/Barley/Morex_v3/Barley_MorexV3_pseudomolecules_plastids.fasta"
OUT_DIR="/panfs/roc/groups/9/morrellp/shared/Datasets/Alignments/nanopore_morex/Morex_85x_ont"
NUM_THREADS="16"

#-----------------
# Make output directory
mkdir -p ${OUT_DIR}

# Check if BAM file is indexed, if not index it
# Note: this may need to be changed to CSI indexing depending on
#   if we are dealing with the parts reference or pseudomolecular reference
if ! [ -f "${BAM}.csi" ]; then
    # Generate CSI index
    echo "Generating CSI index for BAM file..."
    samtools index -bc ${BAM}
fi

OUT_PREFIX=$(basename ${BAM} .bam)

# Output VCF
sniffles --input ${BAM} \
    --vcf ${OUT_DIR}/${OUT_PREFIX}.vcf \
    --reference ${REF} \
    --threads ${NUM_THREADS}
