#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --mem=30gb
#SBATCH --tmp=22gb
#SBATCH -t 06:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=liux1299@umn.edu
#SBATCH -p small,ram256g,ram1t
#SBATCH -o %j.out
#SBATCH -e %j.err

set -e
set -o pipefail

# This script aligns Nanopore trimmed fastq files using Vulcan and outputs in SAM format.
#   https://gitlab.com/treangenlab/vulcan

# Dependencies
module load python3/3.8.3_anaconda2020.07_mamba
# Activate conda environment
# This conda environment contains the modified vulcan script
source activate /panfs/roc/groups/9/morrellp/liux1299/.conda/envs/vulcan_env

# User provided input arguments
# Morex-sample2 reads concatenated into one file
NP_READS="/panfs/roc/groups/9/morrellp/shared/Datasets/Alignments/nanopore_mutated_barley/trimmed_fastq/M20-2-2-20-53_trimmed.fastq.gz"
# Custom Minimap2 alignments with @SQ headers added
FULL_SAM="/scratch.global/liux1299/nanopore_mutated_barley/read_mapping/M20-2-2-20-53_with_SQheaders.sam"
# Only primary mappings with @SQ headers added
FULL_PRIMARY_SAM="/scratch.global/liux1299/nanopore_mutated_barley/read_mapping/M20-2-2-20-53_full_primary.sam"
REF="/panfs/roc/groups/9/morrellp/shared/References/Reference_Sequences/Barley/Morex_v3/Barley_MorexV3_pseudomolecules_parts.fasta"
# Full output directory will be ${OUT_DIR}/${OUT_PREFIX}
OUT_PREFIX="M20_ont_partsRefv3"
OUT_DIR="/panfs/roc/groups/9/morrellp/shared/Datasets/Alignments/nanopore_mutated_barley"
NUM_THREADS="16"

#-----------------
# Run program
# Vulcan automatically makes the output directory
#   but the final BAM file gets output in the out directory so we'll make the dir
#   and cd into the working directory
mkdir -p ${OUT_DIR}/${OUT_PREFIX}
cd ${OUT_DIR}/${OUT_PREFIX}

# --full_sam and --full_sam_primary are custom flags that Chaochih added to handle custom Minimap2 alignments
vulcan --input ${NP_READS} \
    --full_sam ${FULL_SAM} \
    --full_sam_primary ${FULL_PRIMARY_SAM} \
    --reference ${REF} \
    -ont \
    --work_dir ${OUT_DIR}/${OUT_PREFIX} \
    --threads ${NUM_THREADS} \
    --output ${OUT_PREFIX}
