#!/bin/bash
#PBS -l mem=16gb,nodes=1:ppn=12,walltime=01:00:00
#PBS -m abe
#PBS -M liux1299@umn.edu
#PBS -q mesabi

set -e
set -o pipefail

module load bcftools/1.9
module load htslib/1.9

# Removes complex variants (>=3 in length) in REF and ALT alleles columns

# User provided arguments
# List of full filepaths to VCF files
VCF_LIST="/panfs/roc/groups/9/morrellp/shared/Projects/Mutant_Barley/longranger/combined_mutated/phased_variants_fixRef_vcf_list.txt"

VCF=$(cat "${VCF_LIST}" | sed "${PBS_ARRAYID}q;d")

function RemoveComplexVar() {
    local vcf="$1"
    out_dir=$(dirname ${vcf})
    file_name=$(basename ${vcf} .vcf.gz)
    accession=$(basename ${vcf} _new_samp_name_phased_variants_fixRef.vcf.gz)
    # Keep a record of complex variants we removed
    bcftools filter \
        -i 'STRLEN(REF) > 2 | STRLEN(ALT) > 2' \
        -o ${out_dir}/removed_complex_variants_${accession}.vcf \
        -O v \
        ${vcf}
    # Create a VCF that excludes the complex variants
    # We want to keep SNDs: STRLEN(REF) == 2 && STRLEN(ALT) == 1
    # and keep SNIs: STRLEN(REF) == 1 && STRLEN(ALT) == 2
    bcftools filter \
        -e 'STRLEN(REF) > 2 | STRLEN(ALT) > 2' \
        -o ${out_dir}/${file_name}_noComplex.vcf.gz \
        -O z \
        ${vcf}
    # Index the vcf file
    bcftools index \
        ${out_dir}/${file_name}_noComplex.vcf.gz \
        -t \
        -o ${out_dir}/${file_name}_noComplex.vcf.gz.tbi
}

export -f RemoveComplexVar

# Run function on each VCF file
RemoveComplexVar ${VCF}
