#!/bin/bash
#PBS -l mem=8gb,nodes=1:ppn=8,walltime=02:00:00
#PBS -m abe
#PBS -M liux1299@umn.edu
#PBS -q mesabi

set -e
set -o pipefail

# Dependencies
module load bcftools/1.9

# User provided input arguments
VCF_MUT=/panfs/roc/groups/9/morrellp/shared/Projects/Mutant_Barley/longranger_morex_v2/combined_mutated/mut_3_lines.vcf.gz
VCF_MOREX=/panfs/roc/groups/9/morrellp/shared/Projects/Mutant_Barley/longranger_morex_v2/morex-sample2/morex-sample2_concat.vcf.gz

SAMPLE_PREFIX_MUT=$(basename ${VCF_MUT} .vcf.gz)
SAMPLE_PREFIX_MOREX=$(basename ${VCF_MOREX} .vcf.gz)

OUT_DIR_MUT=$(dirname ${VCF_MUT})
OUT_DIR_MOREX=$(dirname ${VCF_MOREX})

# Sort VCF
bcftools sort ${VCF_MUT} -o ${OUT_DIR_MUT}/${SAMPLE_PREFIX_MUT}_sorted.vcf.gz -O z
bcftools sort ${VCF_MOREX} -o ${OUT_DIR_MOREX}/${SAMPLE_PREFIX_MOREX}_sorted.vcf.gz -O z

# Index concatenated files
bcftools index ${OUT_DIR_MUT}/${SAMPLE_PREFIX_MUT}_sorted.vcf.gz -t -o ${OUT_DIR_MUT}/${SAMPLE_PREFIX_MUT}_sorted.vcf.gz.tbi
bcftools index ${OUT_DIR_MOREX}/${SAMPLE_PREFIX_MOREX}_sorted.vcf.gz -t -o ${OUT_DIR_MOREX}/${SAMPLE_PREFIX_MOREX}_sorted.vcf.gz.tbi
