#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --mem=8gb
#SBATCH --tmp=6gb
#SBATCH -t 16:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=liux1299@umn.edu
#SBATCH -p small,ram256g,ram1t
#SBATCH -o %j.out
#SBATCH -e %j.err

set -e
set -o pipefail

# User defined input arguments
FASTQ_LIST="/scratch.global/liux1299/sra_pacbio/adapter_filtered_fastq/adapter_filtered_morex_pacbio_list.txt"
OUT_PREFIX="Morex_pacbio"
OUT_DIR="/scratch.global/liux1299/sra_pacbio/concat_fastq"

#-----------------
# Start from clean slate since we are appending to a file
#   If file exists at start of this job, delete it
if [ -f ${OUT_DIR}/${OUT_PREFIX}.fastq ]
then
    # File exists, remove before concatenating and appending
    rm ${OUT_DIR}/${OUT_PREFIX}.fastq
fi

# Concatenate FASTQ files into single file
for i in $(cat ${FASTQ_LIST})
do
    zcat ${i} >> ${OUT_DIR}/${OUT_PREFIX}.fastq
done

# Compress FASTQ file
gzip ${OUT_DIR}/${OUT_PREFIX}.fastq
