#!/bin/bash
#PBS -l mem=16gb,nodes=1:ppn=12,walltime=00:30:00
#PBS -m abe
#PBS -M liux1299@umn.edu
#PBS -q mesabi

set -e
set -o pipefail

module load bcftools/1.9

# Removes mismatching REF allele positions using job arrays.

# User provided arguments
# IMPORTANT: Make sure vcf list and log list are sorted in the same order
# List of large_svs vcfs
VCF_LIST="/panfs/roc/groups/9/morrellp/shared/Projects/Mutant_Barley/longranger_morex_v2/largeSVs_mutated_vcf_list.txt"
# List of log files containing REF_MISMATCH identifiers
# See CL notes for how log files were created
LOG_LIST="/panfs/roc/groups/9/morrellp/shared/Projects/Mutant_Barley/longranger_morex_v2/largeSVs_targets_log_list.txt"

VCF=$(cat ${VCF_LIST} | sed "${PBS_ARRAYID}q;d")
TARGETS=$(cat ${LOG_LIST} | sed "${PBS_ARRAYID}q;d")
FILE_NAME=$(basename ${VCF} .vcf.gz)
SAMPLE_NAME=$(basename ${VCF} _new_samp_name_large_svs.vcf.gz)
OUT_DIR=$(dirname ${VCF})

# Create targets file of REF_MISMATCH from log files
grep "REF_MISMATCH" ${TARGETS} | cut -f 2,3 > ${OUT_DIR}/ref_mismatch_${SAMPLE_NAME}_large_svs_targets.txt

# Remove positions where REF allele mismatches
bcftools filter \
    -T ^${OUT_DIR}/ref_mismatch_${SAMPLE_NAME}_large_svs_targets.txt \
    -o ${OUT_DIR}/${FILE_NAME}_noRefMismatch.vcf.gz \
    -O z \
    ${VCF}

# Index vcf files
bcftools index \
    ${OUT_DIR}/${FILE_NAME}_noRefMismatch.vcf.gz \
    -t \
    -o ${OUT_DIR}/${FILE_NAME}_noRefMismatch.vcf.gz.tbi
