#!/bin/bash
#PBS -l mem=12gb,nodes=1:ppn=8,walltime=01:00:00
#PBS -m abe
#PBS -M liux1299@umn.edu
#PBS -q lab

set -e
set -o pipefail

# Dependencies
module load bcftools/1.9

# User provided input arguments
# List of VCF files to merge
VCF1_DIR=/panfs/roc/groups/9/morrellp/shared/Projects/Mutant_Barley/longranger/M01-3-3-self5
VCF2_DIR=/panfs/roc/groups/9/morrellp/shared/Projects/Mutant_Barley/longranger/M20-2-2-self5
VCF3_DIR=/panfs/roc/groups/9/morrellp/shared/Projects/Mutant_Barley/longranger/M29-2-2-self5
OUT_DIR=/panfs/roc/groups/9/morrellp/shared/Projects/Mutant_Barley/longranger/combined_mutated
PREFIX=test_mutated_3_lines

# Test merge phased variants VCF files
# phased variants
# bcftools merge ${VCF1_DIR}/M01-3-3_new_samp_name_phased_variants_fixRef_noComplex_f1.vcf.gz \
#     ${VCF2_DIR}/M20-2-2_new_samp_name_phased_variants_fixRef_noComplex_f1.vcf.gz \
#     ${VCF3_DIR}/M29-2-2_new_samp_name_phased_variants_fixRef_noComplex_f1.vcf.gz \
#     -o ${OUT_DIR}/${PREFIX}_merged.vcf -O v --threads 8

# large SVs
bcftools merge ${VCF1_DIR}/M01-3-3_new_samp_name_large_svs_noRefMismatch_f1.vcf.gz \
    ${VCF2_DIR}/M20-2-2_new_samp_name_large_svs_noRefMismatch_f1.vcf.gz \
    ${VCF3_DIR}/M29-2-2_new_samp_name_large_svs_noRefMismatch_f1.vcf.gz \
    -o ${OUT_DIR}/${PREFIX}_merged.vcf -O v --threads 8
