#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --mem=6gb
#SBATCH --tmp=4gb
#SBATCH -t 00:10:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=liux1299@umn.edu
#SBATCH -p small,ram256g,ram1t
#SBATCH -o %j.out
#SBATCH -e %j.err

set -e
set -o pipefail

# This script converst VCF to Annovar's input file format

# Dependencies
export PATH=${PATH}:/panfs/roc/groups/9/morrellp/shared/Software/annovar

# User provided input arguments
annovar_input="/panfs/roc/groups/9/morrellp/shared/Projects/Mutant_Barley/results/Annovar/HC/mut_3_lines_filtered_singletons_only_annovar_input.txt"
# Full filepath to output directory
#   This directory should also contain the database fasta file
out_dir="/panfs/roc/groups/9/morrellp/shared/Projects/Mutant_Barley/results/Annovar/HC"
# This must match the *refGene.txt file
#   Example: HV_Morex_v2_HC_refGene.txt should have build version HV_Morex_v2_HC
build_version="HV_Morex_v2_HC"

#-----------------
# Check if out directory exists, if not make it
mkdir -p ${out_dir}

annotate_variation.pl --geneanno --dbtype refGene --buildver ${build_version} ${annovar_input} ${out_dir}/
